version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=True
      - FLASK_APP=app.py
    env_file:
      - .env
    command: python app.py
